# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-05 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('prn_status', models.CharField(max_length=3)),
                ('prn_model', models.CharField(max_length=8)),
                ('prn_inventory', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('prn_cabinet', models.CharField(max_length=5)),
                ('prn_socket', models.CharField(max_length=26)),
                ('prn_ip', models.CharField(max_length=15)),
                ('prn_network_name', models.CharField(max_length=15)),
                ('prn_sn', models.CharField(max_length=20)),
                ('prn_mac', models.CharField(max_length=12)),
            ],
        ),
    ]
